name: checkov
on: 
  workflow_call:
  
jobs: 
  scan: 
    runs-on: ubuntu-latest
    steps: 
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
           name: test.tf
      - run: terraform fmt -check
      - name: checkov Github Action
        uses: bridgecrewio/checkov-action@12
        with: 
          output_format: cli,sarif
          output_file_path: console,results.sarif
  
    
